flowchart LR
    Home([You are here])
    Home --> Adopter{I want to<br/>use pyarnes}
    Home --> Maintainer{I want to<br/>work on pyarnes}
    Adopter --> E1[Evaluate]
    Adopter --> B1[Bootstrap]
    Adopter --> Bu1[Build]
    Maintainer --> O1[Onboard]
    Maintainer --> Ex1[Extend]
    Maintainer --> R1[Release]
