"""Tests for the specs-viewer helpers.

Each test anchors on ground truth derived independently of the parser
(by hand-reading the markdown, walking the filesystem differently, or
checking the JSON shape against the JS contract). A test that re-derived
its expectation from the same regex it's supposed to guard would only
prove the author can copy a pattern.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

# scripts/serve_specs.py is a uv inline-script; load it directly so the
# tests don't depend on a `scripts` package on sys.path. The module must
# be registered in sys.modules before exec_module so dataclass() can
# resolve its enclosing module by name.
_SPEC_PATH = Path(__file__).resolve().parents[2] / "scripts" / "serve_specs.py"
_spec = importlib.util.spec_from_file_location("serve_specs", _SPEC_PATH)
assert _spec is not None and _spec.loader is not None
serve_specs = importlib.util.module_from_spec(_spec)
sys.modules["serve_specs"] = serve_specs
_spec.loader.exec_module(serve_specs)


# Hand-extracted from specs/consolidation/00-overview.md by reading the
# table directly. NOT generated by the parser. If the file changes, this
# constant has to be updated by hand — that is the point: the test
# enforces a deliberate contract change instead of silent drift.
EXPECTED_OVERVIEW_EDGES: dict[str, list[str]] = {
    "01": ["05", "06", "07", "08", "10", "13", "14", "15", "16", "18"],
    "05": ["07"],
    "06": ["07", "08", "12", "13"],
    "07": ["09", "10", "15", "16", "18"],
    "08": ["06", "07", "15", "16"],
    "09": ["07", "10"],
    "10": ["09", "15", "16"],
    "12": ["06", "13", "14"],
    "13": ["06", "12", "14"],
    "14": ["07", "12", "13"],
    "15": ["08", "16", "20"],
    "16": ["10", "15", "20"],
    "18": ["01", "07"],
    "20": ["10", "15", "16"],
}


class TestDependencyEdgesAgainstRealOverview:
    """The parser must produce the same edges a human reader pulls
    off the actual 00-overview.md. This is the contract test."""

    def test_matches_hand_extracted_edges(self) -> None:
        overview = serve_specs.CONSOLIDATION_ROOT / "00-overview.md"
        assert overview.is_file(), "fixture for the contract test is missing"
        # Bust the lru_cache so the test reflects the file at this moment.
        serve_specs._extract_dependency_edges.cache_clear()
        assert serve_specs._extract_dependency_edges(str(overview)) == EXPECTED_OVERVIEW_EDGES

    def test_no_orphan_targets(self) -> None:
        """Every spec referenced as a dependency target must itself
        exist as a markdown file. Catches typos in the source table
        without re-running the parser's own logic."""
        edges = serve_specs._extract_dependency_edges(str(serve_specs.CONSOLIDATION_ROOT / "00-overview.md"))
        targets = {t for ts in edges.values() for t in ts}
        for spec_num in targets:
            matches = list(serve_specs.CONSOLIDATION_ROOT.glob(f"{spec_num}-*.md"))
            assert matches, f"target {spec_num!r} has no matching spec file"


class TestDependencyEdgesEdgeCases:
    """Negative paths the production parser must survive without raising."""

    def test_missing_file_returns_empty(self, tmp_path: Path) -> None:
        # Non-existent path → silent {} (server keeps booting).
        result = serve_specs._extract_dependency_edges(str(tmp_path / "does-not-exist.md"))
        assert result == {}

    def test_missing_section_returns_empty(self, tmp_path: Path) -> None:
        f = tmp_path / "stub.md"
        f.write_text("# Overview\n\nNo dependency map here.\n", encoding="utf-8")
        assert serve_specs._extract_dependency_edges(str(f)) == {}


class TestPageEntriesMatchSidebar:
    """The data-island page list must equal what the sidebar walker
    sees, otherwise the command palette and prev/next pager will
    disagree with the visible nav."""

    def test_includes_landing_overview_consolidation_diagrams(self) -> None:
        entries = serve_specs._build_page_entries()
        slugs_by_group = {group: [e.slug for e in entries if e.group == group] for group in {e.group for e in entries}}

        # Ground truth: walk the filesystem with a glob the parser
        # doesn't share. If both methods agree, the index is faithful.
        expected_consolidation = sorted(
            p.stem for p in serve_specs.CONSOLIDATION_ROOT.glob("*.md") if p.name != "README.md"
        )
        expected_diagrams = sorted(p.stem for p in serve_specs.DIAGRAMS_ROOT.glob("*.html"))

        assert slugs_by_group["Overview"] == ["readme"]
        assert slugs_by_group["Consolidation"] == expected_consolidation
        assert slugs_by_group["Diagrams"] == expected_diagrams

    def test_landing_title_matches_first_h1(self) -> None:
        entries = serve_specs._build_page_entries()
        landing = next(e for e in entries if e.slug == "readme")
        first_line = serve_specs.LANDING_PAGE.read_text(encoding="utf-8").splitlines()[0]
        assert first_line.startswith("# ")
        assert landing.title == first_line[2:].strip()


class TestDataIslandShape:
    """The JSON shape is the contract between Python and specs.js.
    Pin every key the JS reads — silent renames or missing keys break
    the palette / drawer / artifacts without an obvious failure."""

    @pytest.fixture
    def parsed(self) -> dict[str, object]:
        rendered = serve_specs._render_data_island(serve_specs.LANDING_PAGE)
        prefix = '<script id="__specs_index__" type="application/json">'
        suffix = "</script>"
        assert rendered.startswith(prefix) and rendered.endswith(suffix)
        body = rendered[len(prefix) : -len(suffix)]
        # Reverse the </ defang the renderer applies.
        return json.loads(body.replace("<\\/", "</"))

    def test_top_level_keys(self, parsed: dict[str, object]) -> None:
        # specs.js + Alpine / HTMX consumers expect every key listed here.
        # If new keys are added the test should grow alongside them, not be
        # loosened to a subset check.
        assert set(parsed) == {
            "pages",
            "current",
            "deps",
            "artifacts",
            "spec_headers",
            "topic_chips",
        }

    def test_pages_have_required_fields(self, parsed: dict[str, object]) -> None:
        pages = parsed["pages"]
        assert isinstance(pages, list) and pages
        for page in pages:
            assert set(page) == {"slug", "title", "group", "href"}

    def test_artifacts_keys_match_placeholder_contract(self, parsed: dict[str, object]) -> None:
        # specs.js looks up data via div[data-artifact="<key>"] — these
        # three keys are wired to the three markdown placeholder edits.
        assert set(parsed["artifacts"]) == {"error-tree", "lifecycle-fsm", "hook-wiring"}

    def test_script_tag_defangs_closing_script(self) -> None:
        # An emitted JSON containing the literal "</script" would break
        # the surrounding HTML. The renderer must escape it.
        rendered = serve_specs._render_data_island(serve_specs.LANDING_PAGE)
        # Strip the trailing legitimate </script> close tag, then ensure
        # no other "</script" appears inside the JSON body.
        body = rendered[: -len("</script>")]
        assert "</script" not in body


# ---------------------------------------------------------------------------
# Second-pass helpers (spec-meta, spec-header, spec-card, staleness, tags).
# Oracles are hand-derived from the actual spec text so the tests catch real
# regressions, not paraphrase the parser.
# ---------------------------------------------------------------------------


class TestSpecMetaComputation:
    """Reading-time and section count are deterministic functions of body
    HTML; assert against ground-truth markup independent of the parser."""

    def test_reading_time_uses_220_wpm_and_minimum_one(self) -> None:
        body = "<h1>x</h1><p>" + " ".join(["word"] * 22) + "</p>"
        meta = serve_specs._compute_spec_meta(serve_specs.LANDING_PAGE, body)
        assert meta.reading_minutes == 1

    def test_reading_time_rounds_up(self) -> None:
        body = "<h1>x</h1><p>" + " ".join(["word"] * 221) + "</p>"
        meta = serve_specs._compute_spec_meta(serve_specs.LANDING_PAGE, body)
        assert meta.reading_minutes == 2

    def test_section_count_matches_h2_only(self) -> None:
        body = "<h1>x</h1><h2>a</h2><p>p</p><h2 id='b'>b</h2><h3>c</h3>"
        meta = serve_specs._compute_spec_meta(serve_specs.LANDING_PAGE, body)
        assert meta.section_count == 2  # h3 doesn't count

    def test_inject_meta_skips_when_no_h1(self) -> None:
        body = "<p>no h1 here</p>"
        meta = serve_specs.SpecMeta(reading_minutes=3, section_count=2, last_edited_relative=None)
        out = serve_specs._inject_spec_meta(body, meta)
        assert out == body  # unchanged

    def test_inject_meta_appears_after_h1(self) -> None:
        body = "<h1>Title</h1><p>p</p>"
        meta = serve_specs.SpecMeta(reading_minutes=4, section_count=3, last_edited_relative="2 days ago")
        out = serve_specs._inject_spec_meta(body, meta)
        # The chip lives between the closing </h1> and the next paragraph.
        assert '<div class="spec-meta">' in out
        assert "4 min read" in out
        assert "3 sections" in out
        assert "last edited 2 days ago" in out
        assert out.index('class="spec-meta"') > out.index("</h1>")
        assert out.index('class="spec-meta"') < out.index("<p>")


class TestSpecMetaGitFallback:
    """Git lookup must never crash the server."""

    def test_untracked_file_returns_none(self, tmp_path: Path) -> None:
        f = tmp_path / "untracked.md"
        f.write_text("# untracked\n", encoding="utf-8")
        meta = serve_specs._compute_spec_meta(f, "<h1>x</h1>")
        assert meta.last_edited_relative is None

    def test_tracked_file_returns_string_or_none(self) -> None:
        meta = serve_specs._compute_spec_meta(
            serve_specs.CONSOLIDATION_ROOT / "00-overview.md",
            "<h1>x</h1>",
        )
        assert meta.last_edited_relative is None or isinstance(meta.last_edited_relative, str)


class TestSpecHeaderExtraction:
    """The parser must produce the same header a human reader pulls off
    the spec. Oracle is hand-derived from the actual file."""

    def test_07_swarm_api_header_matches(self) -> None:
        path = serve_specs.CONSOLIDATION_ROOT / "07-swarm-api.md"
        if not path.is_file():
            pytest.skip("07-swarm-api.md is not present in this corpus")
        header = serve_specs._spec_header_for(path)
        assert header is not None
        assert header.title is not None and "swarm" in header.title.lower()
        # Tags were seeded by hand with the curated set; verify intent.
        assert "api" in header.tags
        assert "lifecycle" in header.tags
        assert header.status == "active"

    def test_missing_file_returns_none(self, tmp_path: Path) -> None:
        f = tmp_path / "no-header.md"
        f.write_text("# stub\n\nbody only, no header table\n", encoding="utf-8")
        assert serve_specs._spec_header_for(f) is None

    def test_header_without_tags_row_returns_empty_tuple(self, tmp_path: Path) -> None:
        f = tmp_path / "bare.md"
        f.write_text(
            "# stub\n\n"
            "> **Spec header**\n"
            ">\n"
            "> | Field | Value |\n"
            "> |---|---|\n"
            "> | **Title** | Bare |\n"
            "> | **Status** | active |\n",
            encoding="utf-8",
        )
        header = serve_specs._spec_header_for(f)
        assert header is not None
        assert header.tags == ()

    def test_tag_normalisation(self, tmp_path: Path) -> None:
        f = tmp_path / "tagged.md"
        f.write_text(
            "# stub\n\n"
            "> **Spec header**\n"
            ">\n"
            "> | Field | Value |\n"
            "> |---|---|\n"
            "> | **Title** | Tagged |\n"
            "> | **Tags** | Foo, BAR ,  baz, foo |\n",
            encoding="utf-8",
        )
        header = serve_specs._spec_header_for(f)
        assert header is not None
        # Lowercased, deduped, order preserved.
        assert header.tags == ("foo", "bar", "baz")


class TestStalenessClass:
    """Staleness is a deterministic function of the date diff. Frozen
    `today` so the test stays stable."""

    def test_recent_at_zero_days(self) -> None:
        today = serve_specs._dt.date(2026, 5, 1)
        cls, label = serve_specs._staleness_class("2026-05-01", today=today)
        assert cls == "recent"
        assert label == "✓ recent"

    def test_stale_after_60_days(self) -> None:
        today = serve_specs._dt.date(2026, 5, 1)
        cls, _ = serve_specs._staleness_class("2026-03-02", today=today)  # 60 days
        assert cls == "stale"

    def test_very_stale_past_90_days(self) -> None:
        today = serve_specs._dt.date(2026, 5, 1)
        cls, _ = serve_specs._staleness_class("2026-01-01", today=today)  # 120 days
        assert cls == "very-stale"

    def test_missing_when_none(self) -> None:
        cls, label = serve_specs._staleness_class(None)
        assert cls == "missing"
        assert "missing" in label.lower()

    def test_missing_when_unparseable(self) -> None:
        cls, _ = serve_specs._staleness_class("not-a-date")
        assert cls == "missing"


class TestSpecCardRendering:
    """Spec card must surface every field the reader expects."""

    def test_renders_status_pill_and_topics_and_actions(self) -> None:
        path = serve_specs.CONSOLIDATION_ROOT / "07-swarm-api.md"
        if not path.is_file():
            pytest.skip("07-swarm-api.md is not present in this corpus")
        header = serve_specs._spec_header_for(path)
        assert header is not None
        page_index = {entry.slug: entry for entry in serve_specs._build_page_entries()}
        html_out = serve_specs._render_spec_card(header, "07-swarm-api", page_index)
        assert 'class="spec-card"' in html_out
        assert "spec-status spec-status--active" in html_out
        assert 'class="spec-card-tags"' in html_out
        assert "Open in dep-graph" in html_out
        # Cross-references should render as <a class="spec-ref">.
        assert 'class="spec-ref"' in html_out


class TestTopicChipsAggregation:
    """Topic chips are derived from every spec's Tags row."""

    def test_topic_chips_only_above_threshold(self) -> None:
        # Default filter drops tags appearing in fewer than 3 specs to keep
        # the chip strip compact. Counts must respect the threshold.
        chips = dict(serve_specs._all_topic_chips())
        assert chips, "expected at least one tag with >=3 occurrences"
        for tag, count in chips.items():
            assert isinstance(count, int) and count >= 3, (tag, count)

    def test_topic_chips_min_count_parameter(self) -> None:
        # Lowering the threshold surfaces tags that the default would hide.
        with_low = dict(serve_specs._all_topic_chips(min_count=1))
        with_default = dict(serve_specs._all_topic_chips())
        assert set(with_default).issubset(with_low)
        assert len(with_low) >= len(with_default)

    def test_topic_chips_use_canonical_tags(self) -> None:
        # Synonym folding: `hooks` / `in-process` collapse into `lifecycle`,
        # so the canonical form must be the one that surfaces (when above
        # threshold), and the aliases must not appear as separate chips.
        chips = dict(serve_specs._all_topic_chips(min_count=1))
        assert "hooks" not in chips
        assert "in-process" not in chips
        assert "guardrails" not in chips


class TestSpecHeadersInDataIsland:
    """The data island must expose spec_headers / topic_chips so the
    dep-graph drawer + sidebar Topics filter can render."""

    def test_spec_headers_present(self) -> None:
        rendered = serve_specs._render_data_island(serve_specs.LANDING_PAGE)
        body = rendered[len('<script id="__specs_index__" type="application/json">') : -len("</script>")]
        parsed = json.loads(body.replace("<\\/", "</"))
        assert "spec_headers" in parsed
        assert isinstance(parsed["spec_headers"], dict)
        # At least one seeded entry round-trips.
        assert "07-swarm-api" in parsed["spec_headers"]
        assert "tags" in parsed["spec_headers"]["07-swarm-api"]

    def test_topic_chips_emit_as_pairs(self) -> None:
        rendered = serve_specs._render_data_island(serve_specs.LANDING_PAGE)
        body = rendered[len('<script id="__specs_index__" type="application/json">') : -len("</script>")]
        parsed = json.loads(body.replace("<\\/", "</"))
        assert "topic_chips" in parsed
        chips = parsed["topic_chips"]
        # JSON serialises tuples as lists; each chip is [tag, count].
        for entry in chips:
            assert len(entry) == 2
            assert isinstance(entry[0], str)
            assert isinstance(entry[1], int)
